data:
    dataset: "CIFAR10"
    image_size: 32
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 16

model:
    type: "dit"
    in_channels: 3
    out_ch: 3
    
    # DIT specific parameters
    patch_size: 2
    hidden_size: 384
    depth: 12
    num_heads: 6
    mlp_ratio: 4.0
    class_dropout_prob: 0.1
    num_classes: 10
    learn_sigma: false
    
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: true

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 512
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 10000
    validation_freq: 2000

sampling:
    batch_size: 1000
    last_only: true

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0