data:
  dataset: "CIFAR10"
  image_size: 32
  channels: 3
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: true
  num_workers: 4

model:
  type: "simple"
  var_type: "fixedlarge"
  ema: true
  ema_rate: 0.999
  normalization: "GroupNorm"
  nonlinearity: "swish"
  ch: 128
  ch_mult: [1, 2, 2, 2]
  num_res_blocks: 2
  attn_resolutions: [16, ]
  dropout: 0.1
  resamp_with_conv: true
  conditional: false
  in_channels: 3
  out_ch: 3

diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  num_diffusion_timesteps: 1000

training:
  batch_size: 128
  n_epochs: 800
  n_iters: 500000
  snapshot_freq: 10000
  validation_freq: 2000
  
  # Timestep Importance Sampling Configuration
  use_importance_sampling: true
  importance_ema_decay: 0.99          # EMA decay for loss tracking
  importance_min_prob: 0.1            # Minimum probability per timestep
  importance_warmup_steps: 2000       # Steps of uniform sampling before importance sampling
  importance_update_freq: 200         # How often to update probabilities
  use_importance_weights: true        # Use importance sampling weights in loss

sampling:
  method: "generalized"
  type: "ddpm_noisy"
  step: 250
  eta: 0.0
  skip_type: "uniform"
  base_samples: 1000
  batch_size: 50

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0002
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
  grad_clip: 1.0